# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-2

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: COUD_FORMATION_PKG_PATH
  value: 'aws-cloudformation/'
  readonly: true

stages:
  - stage: firstStage
    jobs:
      - job: readVar
        steps:
          - checkout: none
          - task: Bash@3
            displayName: "variable setter"
            name: varSet
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                FOO='somevalue'
                export EV = FOO
                echo 'ev = '$EV
                echo '##vso[task.setvariable variable=ev;isOutput=true]'$FOO
  - template: template.yml
    parameters:
      APPLICATION : $[stageDependencies.firstStage.readVar.outputs['varSet.FOO']]
     
