# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-2

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: one
  value: initialValue 

steps:
  - template: template.yml  # Template reference
  - script: |
      echo ${{ variables.COUD_FORMATION_PKG_PATH }} # outputs initialValue
    displayName: Display Template variables
  - bash: echo ${{ parameters.APPLICATION  }}
    displayName: Display Template Paramters
