# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-2

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: app2
  value: 'aws-cloudformation/'
  #readonly: true

stages:
  - stage: firstStage
    jobs:
      - job: readVar
        steps:
          - checkout: none
          - task: Bash@3
            displayName: "variable setter"
            name: varSet
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                FOO='somevalue'
                env - NM=V2
                echo 'ev = '$EV
                echo '##vso[task.setvariable variable=FOO;isOutput=true]'$FOO
                echo '##vso[task.setvariable variable=EV;isOutput=true]'$EV
                printenv
          - task: PythonScript@0
            displayName: "print in python"
            name: printByPython
            inputs:
              scriptSource: inline
              script: |
                #code here
                import os
                print 'foo = $(varSet.FOO)'
                print 'ev = $(varSet.EV)'
                print 'foo 1=$VARSET_FOO'
                os.system('echo "foo 1="$VARSET_FOO')
                
      - job: printVar
        dependsOn: readVar
        steps:
          - checkout: none
          - task: Bash@3
            displayName: 'print vars in job printvar'
            name: printVarBash
            inputs:
              targetType: inline
              script: |
                echo '$(FOO)'
                echo '$(EV)'
                printenv
              failOnStderr: true
  - template: template.yml
    parameters:
      APPLICATION : $[stageDependencies.firstStage.readVar.outputs['varSet.FOO']]
